apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: "{replaced with MLflow Project name}"
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: "{replaced with MLflow Project name}"
            image: "{replaced with URI of Docker image created during Project execution}"
            command: ["{replaced with MLflow Project entry point command}"]
          resources:
            limits:
              memory: 512Mi
            requests:
              memory: 256Mi
          restartPolicy: Never
